---
author: Monty Reynolds
categories:
- Moral Worth 
date: "2021-10-04"
draft: false
excerpt: Acting for the reasons which make a moral action the correct one to do.
layout: single
subtitle: Unprincipled Virtue---Acting for the right reasons.
tags:
- style
title: Pretty in Pink 
---

Sometimes a person does the right thing without earning our admiration. Why do these agent's actions prompt us to praise---or blame---when another's would earn the opposite? Because deep moral concern, or its lack, is a signifying mark of a person's character. In other words, the degree of someone's moral concern is a distinguishing (representative) feature of that person's character.

* The moral worth of an action is the extent to which the agent deserves moral praise or blame for performing the action, the extent to which the action speaks well of the agent.

We might typically think that one should reason before acting. Further, it would be strange to think that upon reasoning about what to do, only to fail to do it. You've thought long and hard about going to the party finally deciding that you should go and support your friend on her birthday. 

Responsiveness to Moral Reasons (Praiseworthiness as responsiveness to moral reasons): For an agent to be morally praiseworthy for doing the right thing is for her to have done the right thing for the relevant moral reasons, that is, the reasons making it right (right reasons clause).

As far as you know, she is your friend after all and so you should go though in the end you just cannot bring yourself to do so opting instead to hangout with the poor kids who never get invited to such social events.

Moral responsiveness versus concern for morality: According to the right reasons clause (see 2): A moral agent is not praiseworthy because of self-training or character-building investments undertaken on their own, but because of their moral common sense: their responsiveness to moral reasons is intact [231]. Moral praise is given because of an agent's responsiveness to moral reasons.

Although as far as you can tell, you've committed a grave sin. You stood up your friends and deviated from social convention by crossing the invisible barrier separating your town's economic classes, the haves and have nots. But you just could not bring yourself to...

The concern clause: An agent is more praiseworthy, the stronger the moral concern that has led to her action (233). Blame and moral unresponsiveness: Deficiency (e.g. of perception and motivation) in good will is insufficient responsiveness to moral reasons. And ill will is responsiveness to sinister reasons (reasons that in their essence conflict with morality). 1 and 2 possibly highlight the degree of concern an agent has.

Degrees of Moral Concern: Moral concern is to be understood as concern for what is in fact morally relevant and not as concern for what the agent takes to be morality: Concern is a form of intrinsic desire that people (agent herself) do that which is in fact moral. Surges of emotion is one of three (modestly) reliable indices of concern. The more one cares about morality, the more it colors one's emotional world. E.g., the more you care about something, the more it takes to stop you from acting for its sake. (the other two are cognitive dispositions (e.g. perception). A person concerned with morality is to that degree other things being equal, noticing morally relevant things others might not. (a bird lover will notice a bird on the roof while a person who does not care about birds might not). Motivational dispositions). Acting benevolently on a whim "She is just an ordinary person who does good for moral reasons, but whose moral concern is not deep enough to override some other concerns when they appear" [235].

Deep Moral Concern as a mark of character: The degree of someone's moral concern is a distinguishing (representative) feature of their character. The relevant feature of a morally virtuous character means character marked by deep morally relevant concern. "...the idea that character matters for the moral worth of individual actions makes sense if one takes character to be about depth of concern and not about predictability or frequency" [241]. "To give only one example, suppose that as the Nazis come to power, your long-time fair-weather friend, who has never done you wrong before, cheerfully informs on you. A traditional objection states that virtue ethics is committed to excusing his action as 'out of character.' But if 'in character' does not mean 'predictable,' or 'in keeping with historical trends' then 'unpredictable' and 'out of keeping with trends' does not always mean 'out of character,' either" [241].

Some clarifications: The person who succumbs to actions based on moral reasons against their 'better judgment' lack self-control. But the overall question is whether this is true, and I do not think it is.

