---
bibliography: [/home/redapemusic35/1-2021-22-Projects/references.bib]
title: "Sam the Hero"
weight: 4
subtitle: ""
excerpt: "The Mithrathi's strength is in their non-doxastic faith, emunah to daat."
date: 2021-01-03
draft: false
---

The idea of *emunah to daat* I borrowed from [Samuel Lebens](https://ede99318-8261-4878-a975-f67a7add24ff.filesusr.com/ugd/7cf7e9_98db864fc45b47378a861a21b7da95bc.pdf) in his delightfully interesting paper: *Amen to Daat^[see @lebeNaN]: On the Foundations of Jewish Epistemology.*

---

Silently, the massive imperial structure traversed the sky line, bathing the land below it in a void less mass, shapeless as it was, the shadow along the ground struck fear into its inhabitants, earth bound as they were, they knew, no rather they *believed* that there was no escaping the wrath of the mitrathi; that is until a whisper began to grow throughout their ranks: it is better to die on our feet, rather than live on their knees. They would never forget this day, never again would they trust anyone who did not exhibit their characteristics, their faith, their devotion to the sacred, their love for Hashim, for one another, for living creatures; respect, trust, and awe of his grace and mercy. Never again would they forget this day when they were saved by His might, a salvation that was not perceptible, nor material, but that day, their faith in God was restored and there was never ever any greater salvation which existed in the history of Sol. Sam saw this salvation and though mithrati, was forever changed.

There are two kinds of mithrathi. Visible and indivisible. Mithrathi versus mithrathi prime. The mithrathi are mithrathi, they are committed to principles of law, command, justice. The mithrathi prime believe that they too are committed to these things being mithrathi such as they are. But they have motivations, fears, self defense mechanisms which at times undermines their more broad mithrathi qualities. The mithrathi prime are indistinguishable from mithrathi, such a distinction too, is so fine, they, the mithrathi prime, do not understand such distinctions, being imperceptible as it is. They also hide, or are hidden by the pervasive nature of the broader mithrathi qualities. In the year 10010, when religious attestations where at a 300 year high, the mithrathi proper used the pervading religious belief of the time to justify truth, fairness, loyalty. The mithrathi prime used the times to justify cruelty against outsiders. Four hundred years later, after the mithrathi discovery of
