---
bibliography: [/home/redapemusic35/1-2021-22-Projects/references.bib]
title: "Sam's Phone Call"
weight: 1
subtitle: ""
excerpt: "The Mithrathi's strength is in their non-doxastic faith, emunah to daat."
date: 2021-01-03
draft: false
---

This story is borrowed from Paulina @sliw12's *Defense of Moral Testimony*.

---

> Sam is standing at the shore of a lake when he sees a child beginning to drown. He believes that saving the child would be the good thing to do but it would involve ruining his new expensive suit. He cannot decide what to do and there is no one else at the lake, so he decides to call a friend whom he takes to be reliable. His friend tells him that he should save the child, and he believes him and saves the child. (Sliwa, 2012)

It isn’t clear why Sam doesn’t know what to do when he sees the child drowning. It’s odd even to himself that he would even consider the value of a stranger’s life to be on par with a cheap suit he purchased off the rack from the Casaba outlet near ArcCorp’s head-quarters in Area 18. The suit itself was a little pricey, but nothing that a simple transport mission couldn’t replace.

Sam is acutely aware of this. But awareness of facts do not often equate to practical ability, not always. While talking to his friend, Commander Hirsch of New Babbitch, he is reminded of their time together during the fall of Linton Messer. During the uprisings preceding the Messer’s fall, Sam was a central figure in the military rebellion which signified the end of Messer’s reign.

If it were not for Sam’s eloquence, passion, and the compassion he showed to the troops under him, the enlistees under his command would never have followed his lead in the dismissal of the orders of the despotic reign. The man who performed the courageous, passionate, and heartfelt exploits which the citizens of the UEE sung songs about, is not the same as the one who now, immobilized looks ahead as the scene before him unfolds.

He wonders if this is the natural consequence of a lifetime, 53 years, of being a willing participant in state sponsored violence, witness to countless mass-casualty events, playing a central role in hundreds if not thousands of central plots to destabilize law and order in the pursuit of unconstrained greed on behalf of the woefully privileged few.

He had initially thought that his role in the rebellion which ultimately ended the chaotic and backward reign of the Messer hierarchy, his clarion call, was evidence of unwarranted grace being bestowed unto him. Sam was absolutely sure in the days and months following his rebellion to the reign of despots, that he had achieved the grace and salvation which he had always thought out of reach.

In the old Earth religion, before his race became a space-fairing civilization, there was a deeply held belief and commitment: only a chosen few warranted universal favor and life eternal. He had always known, that had he been alive then, that he was not one of the chosen few. That he was not selected by the supreme deitic force, to lavish eternal praises to goodness and perfection through the rest of his days and all of eternity.

When Sam was a young child growing on the sparsely populated planet of Elysium IV, this bothered him greatly and to no end. There came a time however, when we would just come to accept it as one would upon realizing they would never be their father’s favorite son. After his leadership in the rebellion however, he thought that those days were behind him. At least until now however, as he stood on the shore of the pond, watching the child drown, not sure what to do and feeling a sense of vulnerability as he pressed the com button and with voice quavering, softly asked his friend what he should do.
