---
author: Monty Reynolds 
categories:
- popular narratives 
date: "2021-01-20"
draft: false
excerpt: Are hip-hop artists autonomous? 
layout: single
subtitle: Are hip-hop artists autonomous?
title: Autonomy and Creativity
---

Cardie B. For instance, many argue that cardie b’s artwork is above reproach because it expresses freedom of expression etc and that it’s representative of a platform that allows her to be who she really is. Doesn’t force her into a box created by social constructs etc. However, there are two ways to look at this issue. On one hand, she’s being “herself” and that’s more admirable than portraying someone that isn’t really her. But we might wonder whether she’s ever been allowed to imagine the kind of person that she “wants” to be. You might think that autonomy means not only being yourself, but getting to decide without pressure, economic or otherwise, who that self will be. This might mean that you are presented with options, examples of others etc. It’s not clear that Cardie B has this sort of freedom, or maybe it is. But for it to be true, we have to imagine a world wherein she ***believes*** that she can do and ***be*** otherwise.
