---
title: "Sam and Mary"
weight: 3
subtitle: "Culinary practices in foreign cultures"
excerpt: "Mary n'est pas un veggie."
date: 2021-01-03
draft: false
---

## Mary

Mary has always enjoyed eating meat but recently has accepted a contract to deliver 1000 tons of animal product to Hutton Orbital in Alpha Centauri.[^1][^2] From the moment she landed in the ship hanger at London Relay, her senses were assaulted by the aromas and sounds of hundreds of thousands of species, clamoring fruitlessly against their constraints, their natures never for a minute allowing them to rest, in the peaceful acceptance of their impending fate. It was then she realized that it raised some moral issues. Rather than thinking further about these however, she talks to a friend, Sam, who tells her that eating meat is wrong. Mary knows that her friend is normally trust worthy and reliable, so she believes him and accepts that eating meat is wrong.

## Oh Mary

Mary, being Mithrathi, has always ceremoniously enjoyed eating meat. Recently however, she has accepted a contract to deliver 1000 tons of animal product to Hutton Orbital in Alpha Centauri. She has been informed that this product would not be a part of any ceremonial practices. Further, from the moment she landed in the ship hanger at London Relay, her senses were assaulted by the aromas and sounds of hundreds of thousands of species, clamoring fruitlessly against their constraints, their natures never for a minute allowing them to rest in peaceful acceptance of their impending fate.

Sure the Mithrathi’s own practices of meat production where fairly similar, however, there was purpose behind such displays. Their ceremonial practices were deeply important to their cultural heritage. Without such displays, Mary finds it difficult to imagine having any identity whatsoever.

It was then she realized that it raises some moral issues. Rather than thinking further about these however, she talks to a friend, Sam, who tells her that eating meat is wrong. Mary knows that her friend is normally trust worthy and reliable, so she believes him and accepts that eating meat is wrong.

## Oh, Oh Mary

Oh the horror! Mary has never eaten, nor will she ever, eat meat. She’s Mithrathi and this means that her people have long ago abandoned the absolutely revolting practice of doing so. In fact, the last Mithrathi to take the ceremonial blade to the left ventrical artery of the sacred calf, died over four hundred years ago; when her own mother had just completed her fiftieth revolution, an event not marked with blood letting, but rather opaque sienna; stains of the new era, marked evidences of the new hope. That the Mithrathi, a people whose history mired in blood and nearly drowned in the sins of their past, would finally be able to take their place in the throne rooms of the gods. So no, she would not eat meat, not like these barbarian clients, for which she now toiled. She’s never even had to think about it, nor will she ever need to.

# Notes and References

[^1]: All references to ships, planets etc., taken from the game [Elite Dangerous](https://www.elitedangerous.com/)
[^2]: Mary is a fictional character used in several philosophical thought experiments by @hill09 and @sliw12 among others.
